### PR TITLE
For updating the wikirates to be at parity with master

### PR DESCRIPTION
**Pull request by ShekharDewan**

### CODE REVIEW

**Comment by evscott** [comment]
0 files changed?

**Comment by ShekharDewan** [comment]
Shows me 8, but I'll look again tomorrow

**Comment by evscott** [comment]
Screen Shot 2019-07-18 at 9 47 02 PM
 8 commits but 0 file changes. 🧐

**Comment by ShekharDewan** [comment]
Yes, I was hoping we can bring it to parity in terms of commits. It's just
updating nimeshes branch to catch up with the master so that no conflicts
are written into the code.

**Comment by ShekharDewan** [comment]
Closing as it seems @evscott is right ;)

**Pull request closed without merging**
